const metisAddressList = [
        "Alexander",
        "Alexander First Nation",
        "Alexis",
        "Alexis Nakota Sioux Nation",
        "Allison Bay",
        "Amber River",
        "Assineau River",
        "Athabasca Chipewyan Prairie",
        "Atikameg",
        "Beaver First Nation",
        "Beaver Lake",
        "Beaver Ranch",
        "BeaverLake First Nation",
        "Big Horn",
        "Bigstone Cree Nation",
        "Bistcho Lake",
        "Blood Tribe",
        "Blue QuillsFirst Nation Reserve",
        "Boyer River",
        "Brocket",
        "Buck Lake",
        "Buffalo Lake",
        "Buffalo Lake Metis Settlement",
        "Bushe River",
        "Carcajou Settlement",
        "Cardinal River",
        "Charles Lake",
        "Child Lake",
        "Chiniki",
        "Chipewyan",
        "Chipewyan Prairie First Nation",
        "Clear Hills",
        "Clearwater",
        "Cold Lake",
        "Cold Lake First Nations",
        "Colin Lake",
        "Cornwall Lake",
        "Cowper Lake",
        "Dene Tha' First Nation",
        "Devil's Gate",
        "Dog Head",
        "Driftpile First Nation",
        "Driftpile River",
        "Duncan's",
        "Duncan's First Nation",
        "East Prairie",
        "East Prairie Metis Settlement",
        "Eden Valley",
        "Elizabeth",
        "Elizabeth Metis Settlement",
        "Enoch",
        "Enoch Cree Nation",
        "Ermineskin",
        "Fishing Lake",
        "Fishing Lake Metis Settlement",
        "Fort McKay",
        "Fort McMurray #",
        "Fort Vermilion",
        "Fox Lake",
        "Freeman",
        "Frog Lake First Nation",
        "Gift Lake",
        "Gift Lake Metis Settlement",
        "Goodfish",
        "Goodfish Lake",
        "Gregoire Lake",
        "Grouard",
        "Halcro",
        "Hay Lake",
        "Heart Lake",
        "Heart Lake First Nation",
        "Horse Lake First Nation",
        "House River Indian Cemetery",
        "Irmineskin Tribe",
        "Jackfish Point",
        "Janvier",
        "Jean Baptiste Gambler",
        "John D'or Prairie",
        "Kapawe'no First Nation",
        "Kehewin First Nation",
        "Kikino Metis Settlement",
        "Little Red River Cree Nation",
        "Loon River Cree",
        "Louis Bull",
        "Louis Bull Tribe",
        "Lubicon Lake Band",
        "Makaoo",
        "Maskwacis",
        "Meander River",
        "Mikisew Cree First Nation",
        "Montana",
        "Montana First Nation",
        "Morley",
        "Namur Lake",
        "Namur River",
        "O'Chiese",
        "O'Chiese Cemetery",
        "O'Chiese First Nation",
        "Old Fort",
        "Paddle Prairie",
        "Pakashan",
        "Paul First Nation",
        "Peace Point",
        "Peavine",
        "Peavine Metis Settlement",
        "Peerless Trout First Nation",
        "Peigan",
        "Pigeon Lake",
        "Piikani Nation",
        "Puskiakiwenin",
        "Redwood Meadows",
        "Saddle Lake",
        "Saddle Lake First Nation",
        "Samson",
        "Samson Cree",
        "Sand Point",
        "Sawridge",
        "Sawridge First Nation",
        "Settlements",
        "Siksika",
        "Siksika Nation",
        "Smith's Landing First Nation",
        "Standoff",
        "Stoney",
        "Stoney Tribe",
        "Stony Plain",
        "Sturgeon Lake",
        "Sturgeon Lake Cree Nation",
        "Sucker Creek",
        "Sunchild Cree",
        "Sunchild First Nation",
        "Swan River",
        "Swan River First Nation",
        "Tallcree",
        "Tallcree First Nation",
        "Tsuu T'ina (Sarcee)",
        "Tsuu T'ina Nation",
        "Unipouheos",
        "Upper Hay River",
        "Utikoomak Lake",
        "Wabamun",
        "Wabasca",
        "Wadlin Lake",
        "Wesley",
        "Whitecourt",
        "Whitefish",
        "Whitefish Lake",
        "William Mckenzie",
        "Winefred Lake",
        "Woodland Cree",
        "Woodland Cree First Nation",
        "Zama Lake"
]

// export transformed list with value and text
export default metisAddressList.map(city => ({
    value: city,
    text: city
}));